name: Update next major branch
on:
  push:
    branches:
      - master

jobs:
  run_action:
    runs-on: ubuntu-latest
    steps:
      - name: Merge Follow Branch
        uses: toysmoon/follow_branch@1.0.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target-branch: 3.x
          following-branch: master
